FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json turbo.json ./

RUN npm install turbo && npm install

COPY . .

RUN npm run turbo build

EXPOSE 3001

CMD ["npm", "run", "turbo", "run", "start"]
