services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zaya
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    depends_on:
      - server
    ports:
      - 3001:3001
    networks:
      - app_network
    environment:
      API_URL: http://server:3000
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - app_network
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/zaya
volumes:
  postgres_data: 
networks:
  app_network: